### ISSUE TITLE
Broken 2.0.0 Release

### ISSUE THREAD

**Issue by bierik** [collective/collective.js.jqueryui#31]
According to https://github.com/collective/collective.js.jqueryui/blob/2.0.0/collective/js/jqueryui/common.zcml the current jquery.ui version does not match the master.

See this PR https://github.com/collective/collective.js.jqueryui/pull/30

**Comment by maethu** [comment]
The `common.zcml` on master branch is OK.

It seems like a release issue.

**Comment by maethu** [comment]
@bsuttor Can you make a new 2.0.1 release?

**Comment by bsuttor** [comment]
Done, 
https://pypi.python.org/pypi/collective.js.jqueryui/2.0.1

Sorry, I don't know what happens during 2.0.0 release

**Comment by maethu** [comment]
Thanks!!
