### ISSUE TITLE
Possible release problems

### ISSUE THREAD

**Issue by gforcada** [collective/collective.js.jqueryui#32]
I just noticed (thanks to http://jenkins.plone.org/view/QA/job/qa-code-analysis) that [check-manifest](http://pypi.python.org/pypi/check-manifest) warns about some potential problems when trying to release.

Namely that setuptools_git is not on sources. It's defined as a `setup_requires` in setup.py. I personally never have seen that on any setup.py, so @toutpt would you mind explaining why is that needed? Maybe it's something obsolete? [It was added 3 years ago to make releases better](https://github.com/collective/collective.js.jqueryui/commit/8db563ee830cd6c1db5bc9891d67ae7cd7a95f6d)

**Comment by mauritsvanrees** [comment]
+1 on removing `setuptools_git`. I have done a few minor packaging commits on master (but I have not removed this dependency yet). When I do `python2.7 setup.py sdist` in a checkout compared to in a non-git copy, the non-git copy then misses `bootstrap.py`, `buildout.cfg` and `.gitignore` and that is perfect to me and is also one of my minor changes.

+1 on making a new release (which I wanted to do, but I have no PyPI rights). Please also have a look at issue #34 about version numbering.

PyPI says:

Package Index Owner: bsuttor, davisagli, vincentfretin, rnix, vangheem, toutpt
Package Index Maintainer: bsuttor, gotcha, kiorky, vincentfretin, rnix, vangheem

**Comment by gforcada** [comment]
A quick search on github shows that `setuptools_git` is no longer used, so I think we can safely close this 😄
